services:
  # Backend Service
  - type: web
    name: practika-backend
    runtime: node
    env: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: MONGO_URI
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_CLIENT_CERT_URL
        sync: false

  # Frontend Service
  - type: web
    name: practika-frontend
    runtime: static
    env: static
    region: frankfurt
    plan: free
    rootDir: frontend
    buildCommand: npm install; npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyBUOoIXkkNYDNxwj-_GC1NNL6zxgGW-rNo
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: practika-app-f5ea2.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: practika-app-f5ea2
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: practika-app-f5ea2.firebasestorage.app
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: 440708238791
      - key: VITE_FIREBASE_APP_ID
        value: 1:440708238791:web:83d98a335ff986bc1b9de2
      - key: VITE_API_URL
        sync: false
